### PR TITLE
Fix profile permissions in views

### PR DESCRIPTION
**Pull request by samjackx**
First time doing this, if anything is wrong, tell me.

### CODE REVIEW

**Comment by wisyr** [comment]
Thank you for your effort into ScadaLTS. Please give us your e-mail to precisely discuss all the other details.

**Comment by samjackx** [comment]
Hi,
Email: sammerbf@gmail.com

Cheers.

**Comment by grzesiekb** [comment]
We wrote the email to you.

**Comment by grzesiekb** [comment]
Close

**Pull request closed without merging**
